[mgr]
show_hidden = false
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_symlink = true

[opener]
edit = [
    { run = '${EDITOR:-nvim} "$@"', block = true, for = "unix" },
]
open = [
    { run = 'xdg-open "$@"', desc = "Open", for = "linux" },
]

[plugin]
preloaders = [
    { mime = "application/*zip", run = "ouch" },
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/x-bzip2", run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar", run = "ouch" },
    { mime = "application/x-xz", run = "ouch" },
]
previewers = [
    { mime = "application/*zip", run = "ouch" },
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/x-bzip2", run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar", run = "ouch" },
    { mime = "application/x-xz", run = "ouch" },
]

[git]
show_branch = true
