[mgr]
show_hidden = false
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_symlink = true

[opener]
edit = [
    { run = '${EDITOR:-nvim} %s', block = true, for = "unix" },
]
image = [
    { run = 'loupe %s', orphan = true, desc = "Loupe", for = "linux" },
]
pdf = [
    { run = 'zathura %s', orphan = true, desc = "Zathura", for = "linux" },
]
open = [
    { run = 'xdg-open %s', desc = "Open", for = "linux" },
]

[open]
prepend_rules = [
    { mime = "application/pdf", use = "pdf" },
    { mime = "image/*", use = "image" },
    { mime = "text/*", use = "edit" },
    { mime = "*/javascript", use = "edit" },
    { mime = "application/json", use = "edit" },
]

[plugin]
preloaders = [
    { mime = "application/*zip", run = "ouch" },
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/x-bzip2", run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar", run = "ouch" },
    { mime = "application/x-xz", run = "ouch" },
]
previewers = [
    { mime = "*/", run = "folder", sync = true },
    { mime = "text/*", run = "code" },
    { mime = "*/xml", run = "code" },
    { mime = "*/javascript", run = "code" },
    { mime = "*/x-wine-extension-ini", run = "code" },
    { mime = "application/json", run = "json" },
    { mime = "image/*", run = "image" },
    { mime = "video/*", run = "video" },
    { mime = "application/pdf", run = "pdf" },
    { mime = "application/*zip", run = "ouch" },
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/x-bzip2", run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar", run = "ouch" },
    { mime = "application/x-xz", run = "ouch" },
    # -- Fallback (Everything else is text) --
    { mime = "*", run = "code" },
]

[git]
show_branch = true
