#!/bin/sh

set -e

wal_colors="$HOME/.cache/wal/colors.sh"
dwl_colors="$HOME/.cache/wal/colors-codex-dwl.h"
somebar_config="$HOME/builds/somebar/src/config.hpp"

if [ ! -r "$wal_colors" ]; then
	echo "missing $wal_colors; run wal first" >&2
	exit 1
fi

. "$wal_colors"

hex_to_c() {
	printf "Color(0x%s, 0x%s, 0x%s)" \
		"$(printf "%s" "$1" | cut -c2-3)" \
		"$(printf "%s" "$1" | cut -c4-5)" \
		"$(printf "%s" "$1" | cut -c6-7)"
}

hex_to_dwl() {
	printf "COLOR(0x%sff)" "$(printf "%s" "$1" | cut -c2-7)"
}

cat > "$dwl_colors" <<EOF
/* Generated by ~/.scripts/rebuild-dwl-theme.sh */
#define COLOR(hex)    { ((hex >> 24) & 0xFF) / 255.0f, \\
                        ((hex >> 16) & 0xFF) / 255.0f, \\
                        ((hex >> 8) & 0xFF) / 255.0f, \\
                        (hex & 0xFF) / 255.0f }

static float rootcolor[]   = $(hex_to_dwl "$background");
static float bordercolor[] = $(hex_to_dwl "$color8");
static float focuscolor[]  = $(hex_to_dwl "$color4");
static float urgentcolor[] = $(hex_to_dwl "$color1");
EOF

cat > "$somebar_config" <<EOF
// Generated by ~/.scripts/rebuild-dwl-theme.sh
#pragma once
#include "common.hpp"

constexpr bool topbar = true;

constexpr int paddingX = 8;
constexpr int paddingY = 2;

constexpr const char* font = "JetBrains Mono Nerd Font 11";

constexpr ColorScheme colorInactive = {$(hex_to_c "$foreground"), $(hex_to_c "$background")};
constexpr ColorScheme colorActive = {$(hex_to_c "$foreground"), $(hex_to_c "$color8")};
constexpr const char* termcmd[] = {"kitty", nullptr};

static std::vector<std::string> tagNames = {
	"1", "2", "3",
	"4", "5", "6",
	"7",
};

constexpr Button buttons[] = {
	{ ClkStatusText,   BTN_RIGHT,  spawn,      {.v = termcmd} },
};
EOF

cd "$HOME/builds/somebar"
meson setup build --prefix="$HOME/.local" --wipe >/dev/null
meson compile -C build
meson install -C build

cd "$HOME/builds/dwl"
make

echo "rebuilt somebar and dwl theme files"
